### PR TITLE
Basic theming overrides

### PR DESCRIPTION
**Pull request by sappor0**
- Copy `files/jitsi-meet-override.css` to `/usr/share/jitsi-meet/css/override.css` if it exists
- Patch `/usr/share/jitsi-meet/index.html` with `files/jitsi-meet-index.patch` if it exists

### CODE REVIEW

**Comment by 0x46616c6b** [comment]
Thanks for the contribution! 

Do you think we need the `patch` package here? We can use the ansible `replace` module to ensure the override.css is included.

**Comment by sappor0** [comment]
Good point. I'll update the MR.

**Comment by 0x46616c6b** [comment]
Thanks a lot!

**Comment by sappor0** [comment]
You're welcome :)

**Pull request merged**
