### PR TITLE
Derives passwords/secrets from one base secret

### PR DESCRIPTION
**Pull request by funkyfuture**
this is a follow-up w/ only the proposal for a base secret as follow-up to #25.

### CODE REVIEW

**Comment by t2d** [comment]
Looks like idempotence is broken by this PR

**Comment by funkyfuture** [comment]
i'll probably not have the time too look into this within the next two weeks.

the thing is, from the logs i can't gather how the break of idempotence is detected as a i have the impression that the playbook is applied only once. if you know a good resource that conveys the gist of how these checks work, i'd appreciate if you pointed it out. also, i'm puzzled why Docker is involved in the testing setup.

**Comment by t2d** [comment]
The error message is quite clear: https://travis-ci.com/github/systemli/ansible-role-jitsi-meet/builds/164238339#L609
I recommend to do the local testing with `molecule-vagrant` and then use `molecule converge` multiple times. It shows idempotence errors quite clearly.

**Comment by funkyfuture** [comment]
a'ight i fixed this by using the base secret as salt to the hash function that would then turn to be deterministic.

**Comment by funkyfuture** [comment]
i simplified the password derivation chain. i guess i got hooked on the `password_hash` filter b/c i initially wanted to feed the base secret as salt to it.

**Comment by t2d** [comment]
Thank you. I think this is an amazing feature and smart implementation!

**Pull request merged**
