### PR TITLE
Add custom nginx logrotate config

### PR DESCRIPTION
**Pull request by xshadow**

### CODE REVIEW

**Comment by funkyfuture** [comment]
some remarks:

- the template modules is used though it is in fact a static artifact
- it is opinionated, especially the `rotate' directive should be configurable
- other components (jicofo, jvb, prosody) aren't customized, i adjusted these with `post_tasks` so far

**Comment by xshadow** [comment]
@funkyfuture you could share your customizations via a pull request.

**Comment by funkyfuture** [comment]
do you mean as part of the example playbook in the `README`?

**Comment by funkyfuture** [comment]
ah, i see your recent amendment. well, my approach is different. i have no preference, but only that it should be consistent. so, either configure all w/ the role. or leave the responsibility to the user.

**Comment by xshadow** [comment]
You are more then welcome to share any your code via PR, if you think this role can be improved

**Comment by funkyfuture** [comment]
yeah, but i didn't solve it within the role.

**Pull request merged**
